config/routes.rb
LoveAndLaugh::Application.routes.draw do

  resources :videos

  resources :testimonials

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  resources :photos
  resources :children

  get "children/index"
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/videos"
  get "static_pages/schedule"
  get "static_pages/testimonials"
  root 'static_pages#home'
  get "users/calling_method"
  get "users/send_message"

  resources :users do
    resource :children
    resources :messages
  end

  match '/contacts',     to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  title      :string(255)
#  content    :text
#  user_id    :string(255)
#  created_at :datetime
#  updated_at :datetime
#  parent_id  :integer
#

class Message < ActiveRecord::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_filter :redirect_if_not_admin

  respond_to :html

  def index
    @messages = Message.all
    respond_with(@messages)
  end

  def show
    respond_with(@message)
  end

  def new
    @user = current_user
    @message = Message.new
  end

  def edit
  end

  def create
    @user = current_user
    @message = @user.messages.build(message_params)
    puts message_params
    respond_to do |format|
      if @message.save
        if @message.parent_id.nil?
          admin_broadcast_message
        else
          admin_single_parent_message
        end
        format.html { redirect_to static_pages_home_path, notice: "message successfully created" }
      else
        format.html { render action: "new" }
      end
    end
  end

  def admin_single_parent_message
    UserMailer.send_digest(User.find(@message.parent_id), @message).deliver
  end

  def admin_broadcast_message
    User.all.each do |u|
      UserMailer.send_digest(u, @message).deliver
    end
  end

  def update
    @message.update(message_params)
    respond_with(@message)
  end

  def destroy
    @message.destroy
    respond_with(@message)
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

  def redirect_if_not_admin
    unless current_user.admin?
      redirect_to new_user_registration_path, notice: 'Only admin can view all children'
    end
  end

    def message_params
      params.require(:message).permit(:name, :title, :content, :user_id, :parent_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/edit.html.haml
%h1 Editing message

= render 'form'

= link_to 'Show', @message
\|
= link_to 'Back', messages_path

app/views/messages/index.html.haml
.row
  .large-12.columns
    %h1 Sent Messages

    %table
      %tr
        %th Name
        %th Title
        %th Content
      - @messages.each do |message|
        %tr
          %td= message.name
          %td= message.title
          %td= message.content

app/views/messages/new.html.haml
.row
  .large-12.cols
    %h1 New message

    = simple_form_for [@user, @message] do |f|
      = f.error_notification

      .form-inputs
        = f.input :title
        -#= f.input :content
        -#= f.association :users

        = f.input :content, :as => :ckeditor, :label => 'content', :input_html => { :toolbar => 'Basic', :style => 'width: 90%', :rows => 10 }
      .form-actions
        = f.submit "save", class: :button

app/views/messages/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @message.name
%p
  %b Title:
  = @message.title
%p
  %b Content:
  = @message.content
%p
  %b User:
  = @message.user_id

= link_to 'Edit', edit_message_path(@message)
\|
= link_to 'Back', messages_path