config/routes.rb
LoveAndLaugh::Application.routes.draw do

  resources :videos

  resources :testimonials

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  resources :photos
  resources :children

  get "children/index"
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/videos"
  get "static_pages/schedule"
  get "static_pages/testimonials"
  root 'static_pages#home'
  get "users/calling_method"
  get "users/send_message"

  resources :users do
    resource :children
    resources :messages
  end

  match '/contacts',     to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/video.rb
class Video < ActiveRecord::Base

  def self.public_videos
    Video.all.where(:public => true)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @user = current_user
    if @user && @user.admin?
      @videos = Video.all
    else
      @videos = Video.public_videos
    end
    respond_with(@videos)
  end

  def show
    respond_with(@video)
  end

  def new
    @video = Video.new
    respond_with(@video)
  end

  def edit
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      redirect_to videos_path, :notice => "Successfully Uploaded"
      else
      redirect_to videos_path, :notice => "Failed to upload. Please try again."
    end
  end

  def update
    @video.update(video_params)
    if @video.save
      redirect_to videos_path, :notice => "Successfully Uploaded"
      else
      redirect_to videos_path, :notice => "Failed to upload. Please try again."
    end
  end

  def destroy
    @video.destroy
    respond_with(@video)
  end

  private
    def set_video
      @video = Video.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:public, :youtube_video)
    end
end

app/helpers/videos_helper.rb
module VideosHelper

  def embed url
    url.split("=").last
  end
end

app/views/videos/_form.html.haml
= simple_form_for(@video) do |f|
  = f.error_notification

  .form-inputs
    = f.input :public
    = f.input :youtube_video

  .form-actions
    = f.submit "save", class: :button

app/views/videos/edit.html.haml
.row
  .container
    %h1 Editing video

    = render 'form'

    = link_to 'Show', @video
    \|
    = link_to 'Back', videos_path

app/views/videos/index.html.haml
.row
  .container
    %br
    %br
    - if @user && @user.admin?
      = link_to 'New Video', new_video_path, class: :button
    %h1 Listing videos
    - @videos.each do |video|
      .embed-container
        %iframe{:allowfullscreen => '', :frameborder => '0', :height => '100', :src => "https://www.youtube.com/embed/#{embed video.youtube_video}", :width => '30%'}
      - if @user && @user.admin?
        = link_to 'Destroy', video, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: :button
        = link_to 'Edit', edit_video_path(video), class: :button
      %hr

app/views/videos/new.html.haml
.container
  .row
    %h1 New video

    = render 'form'

    = link_to 'Back', videos_path

app/views/videos/show.html.haml
%p#notice= notice

%p
  %b Public:
  = @video.public
%p
  %b Youtube video:
  = @video.youtube_video

= link_to 'Edit', edit_video_path(@video)
\|
= link_to 'Back', videos_path