config/routes.rb
LoveAndLaugh::Application.routes.draw do

  resources :videos

  resources :testimonials

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  resources :photos
  resources :children

  get "children/index"
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/videos"
  get "static_pages/schedule"
  get "static_pages/testimonials"
  root 'static_pages#home'
  get "users/calling_method"
  get "users/send_message"

  resources :users do
    resource :children
    resources :messages
  end

  match '/contacts',     to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/testimonial.rb
# == Schema Information
#
# Table name: testimonials
#
#  id         :integer          not null, primary key
#  entry      :text
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Testimonial < ActiveRecord::Base
  validate :entry, :presence => true
  belongs_to :user
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @testimonials = Testimonial.all
    respond_with(@testimonials)
  end

  def show
    respond_with(@testimonial)
  end

  def new
    @testimonial = Testimonial.new
    respond_with(@testimonial)
  end

  def edit
  end

  def create
    @testimonial = Testimonial.new(testimonial_params)
    @testimonial.user_id = current_user.id

    respond_to do |format|
      if @testimonial.save!
        format.html {
          redirect_to testimonials_path,
          notice: 'Testimonial was successfully created.'
        }
        format.json { render action: 'show', status: :created, location: @testimonial }
      else
        format.html { render action: 'new' }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @testimonial.update(testimonial_params)
    respond_with(@testimonial)
  end

  def destroy
    @testimonial.destroy
    respond_with(@testimonial)
  end

  private
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    def testimonial_params
      params.require(:testimonial).permit(:entry, :user_id)
    end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.haml
= simple_form_for(@testimonial) do |f|
  = f.error_notification

  .form-inputs
    = f.input :entry,  :as => :text, :input_html => {:rows => 10 }
    -#= f.input :user_id

  .form-actions
    = f.submit "save", class: :button

app/views/testimonials/edit.html.haml
%h1 Editing testimonial

= render 'form'

= link_to 'Show', @testimonial
\|
= link_to 'Back', testimonials_path

app/views/testimonials/index.html.haml
.row
  .large-12.columns
    %h1.headings.text-center Our Testimonials
    %hr
    = link_to 'New Testimonial', new_testimonial_path, class: :button
    %p
    - @testimonials.each do |testimonial|
      = testimonial.entry
      %br
      %p.right ~ #{User.find(testimonial.user_id).name}
      %hr
        %hr
    %p
    Love and Laughter Daycare has been a part of our extended family for the last 5 years. When I needed to look for a daycare option for my older child, I visited several daycares but none of them compared to this particular daycare. I knew I made the right choice when my kid refused to come home with me in the evenings and wanted to continue playing there ! Neeta is always loving and affectionate with tke kids and I know my child will be cared for like he is at home. My older child is now in school but my younger one now goes to this daycare. There was no hesitation at all making the decision to send him here after the first one's experience. Though this is a home based daycare, it is a licensed facility and I am not apprehensive about any aspect of my child's safety or wellbeing. I am glad I chose this particular home based daycare over a bigger facility where my kid may have been lost in the crowd.
    %br
    %p.right ~Deepa
    %hr

    %p
    My son Arthur has been coming here since he was 11 months old and he is now two. Very happy with the love and care that he has received here. It is a great family atmosphere and very different from the other places that are run as a business. I would definitely recommend love and laughter daycare to all.
    %br
    %p.right Dinesh K.

    %hr
    %p
    Neeta's child care center is a great place for babies as well as kids of all ages.
    i have been sending my younger daughter since she was 4 months old. and i am very happy with the way she handles the new child. she includes other fun activities like poems, coloring, art work etc.
    My elder daughter also used to go to the Neeta's child care since she was 12 months. i did not know about her earlier otherwise i would have not send her to anyother place.
    Neeta is certified child care provider.
    %br
    %p.right ~rk k
    %hr
    %p
    My 18 month old used to go to this daycare before i lost my job. The lady Neeta is very experienced and very patient. My child ia a very fussy eatest but Neeta will make sure that kids eat well in the daycare. The place s clean. They spend lot of time outside including going around the block or to the park in their buggy. At the end of the day my kid was always well fed and well rested. Also he learnt so many rhymes at the daycare.
  %br
    %p.right ~rajasri e

app/views/testimonials/new.html.haml
.row
  .large-12.columns
    %h1 New testimonial

    = render 'form'

app/views/testimonials/show.html.haml
%p#notice= notice

%p
  %b Entry:
  = @testimonial.entry
%p
  %b User:
  = @testimonial.user_id

= link_to 'Edit', edit_testimonial_path(@testimonial)
\|
= link_to 'Back', testimonials_path