config/routes.rb
LoveAndLaugh::Application.routes.draw do

  resources :videos

  resources :testimonials

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  resources :photos
  resources :children

  get "children/index"
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/videos"
  get "static_pages/schedule"
  get "static_pages/testimonials"
  root 'static_pages#home'
  get "users/calling_method"
  get "users/send_message"

  resources :users do
    resource :children
    resources :messages
  end

  match '/contacts',     to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

end

app/views/layouts/_footer.html.haml
%footer.row
  .large-12.columns
    %hr/
    .row
      .large-6.columns
        %p  Copyright 2014, Love and laughter DayCare
      .large-6.columns
        %ul.inline-list.right
          / <li><a href="#">Link 1</a></li>
          / <li><a href="#">Link 2</a></li>
          / <li><a href="#">Link 3</a></li>
          / <li><a href="#">Link 4</a></li>

app/views/layouts/_header.html.haml
.row
  .large-2.left.columns
    %h1
      = link_to image_tag("loveandlaughter/logo.png", :border => 0, height: '10px'), static_pages_home_path, {:class => 'dock-item'}
  .large-10.columns
    %ul.button-group
      %li= link_to "Testimonials", testimonials_path, class: :button
      %li= link_to "Contact Us ", contacts_path, class: :button
      -#%li= link_to "Register your kid", new_kid_path, class: :button
      %li= link_to "Photo Gallery", photos_path, class: :button
      %li= link_to "Videos", videos_path, class: :button
      %li= link_to "Schedule", static_pages_schedule_path, class: :button
      - if current_user
        %a.button.dropdown(href="" data-dropdown="drop")
          = truncate(current_user.email, length: 10, omission: '.')
        %ul#drop.f-dropdown(data-dropdown-content)
          %li= link_to 'Edit Profile', edit_user_path(current_user)
          %li= link_to 'Change Email / Password', edit_user_registration_path
          %li= link_to 'Logout', destroy_user_session_path
      - else
        %li
          = link_to 'Log in', new_user_session_path, class: :button
    %ul.button-group
      - if current_user && current_user.admin?
        %li= link_to 'Browse Parents', users_path, class: :button
        %li= link_to 'Browse Children', children_path, class: :button
        %li= link_to 'Message to Parents', new_user_message_path(current_user), class: :button
      -#- if current_user && current_user.children.first.nil?
      -#  - current_user.children.each do |c|
      -#    %li= link_to "#{c.first_name}'s Profile", child_path(c.id), class: :button
    - if current_user && current_user.confirmed?
      - if current_user.children.first.nil?
        = link_to 'Add your child profile', new_user_children_path(current_user), class: :button
      - elsif current_user.children.first.persisted?
        = link_to "Edit #{current_user.children.first.first_name}'s profile", edit_child_path(current_user.children.first), class: :button
        = link_to "#{current_user.children.first.first_name}'s profile", child_path(current_user.children.first), class: :button

app/views/layouts/application.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
%head
  %meta{:charset => "utf-8"}/
  / Uncomment to make IE8 render like IE7
  / <meta http-equiv="X-UA-Compatible" content="IE=7" />
  / Set the viewport width to device width for mobile
  %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
  %meta(name="google-site-verification" content="-U07BwNdRv-cu2SVS1BuL46HWHLEPjUmvtvLpmWIop4")

  %title= content_for?(:title) ? yield(:title) : "Love & Laughter Playschool"
  %link(rel="shortcut icon" href="favicon.ico" type="image/x-icon")
  = stylesheet_link_tag  "application"
  %link{:href => "http://fonts.googleapis.com/css?family=Tangerine", :rel => "stylesheet", :type => "text/css"}/
  = javascript_include_tag "vendor/custom.modernizr"
  = csrf_meta_tags
%body.background
  = render 'layouts/header'
  %br
  = yield
  = render 'layouts/footer'
  = debug(params) if Rails.env.development?
  = javascript_include_tag "application"